#
# This file has been automatically generated by the WICED 20719-B1 Designer.
#

APP_SRC = BLE_App_CO2.c
APP_SRC += BLE_App_CO2_db.c
APP_SRC += wiced_bt_cfg.c

APP_SRC += pasco2.c
APP_SRC += DPS368.c

########################################################################
# Component(s) needed
########################################################################
$(NAME)_COMPONENTS := spp_lib.a

########################################################################
# C flags
########################################################################
C_FLAGS += -DWICED_BT_TRACE_ENABLE

# If defined, HCI traces are sent over transport/WICED HCI interface
C_FLAGS += -DHCI_TRACE_OVER_TRANSPORT

########################################################################
################ DO NOT MODIFY FILE BELOW THIS LINE ####################
########################################################################
C_FLAGS += -DSMUX_CHIP=$(CHIP)
APP_SRC += CO2wiced_platform_pin_config.c
